---
- defmacro:
    name: foo
    args: [who]
    value:
        Hello: who
- foo:
    who: World
---
- define: # <1>
    name: mygit_repo_url
    value: http://my.example.org/mygit.git

- defmacro: # <2>
    name: mygit_materials
    args: [branch_name]
    value:
      mygit:
        git: mygit_repo_url # <3>
        branch: branch_name
---
pipelines:
  mypipe1: 
    group: mygroup
    label_template: "${COUNT}"
    materials: {mygit_materials: {branch_name: master}} # <4>
    stages:

  mypipe2: 
    group: mygroup
    label_template: "${COUNT}"
    materials:
        mygit_materials: 
            branch_name: ci # <5>
    stages:
---
- define: {name: X, value: Christopher}
- define: {name: AXA, value: 'A{{ X }}A'}
---
- AXA: Christopher
# Produces AChristopherA
---
- {python: ' 2**10 '}
---
- define: {name: age, value: 32}
- age
- define: {name: age2, value: [age, age]}
- age2
- define: {name: age2, value: [{define: {name: age, value: 99}}, age]}
- age2
# Produces:
#- 32
#- - 32
#  - 32
#- - 99
---
- define:
    name: data
    value:
        - type: webserver
          hostname: web01
          ip: 1.1.2.3
        - type: database
          hostname: db01
          ip: 1.1.2.2
- data.1.hostname
# produces
- db01
---
defmacro:
  name: app-upgrade
  args: [appname, dbname]
  value:
      Database upgrade:
        - stop application {{ appname }}
        - backup app datbase {{ dbname }}
        - upgrade the database {{ dbname }}
        - restart the application {{ appname }}
        - smoke test {{ appname }}
---
- {app-upgrade: { appname: Netflix, dbname: db8812}}
- app-upgrade:
    appname: Netflix
    dbname: postgres123123
...